spring:
  ai:
    alibaba:
      toolcalling:
        baidutranslate:
          enabled: true
          app-id: ${BAIDU_TRANSLATE_APP_ID}
          secret-key: ${BAIDU_TRANSLATE_SECRET_KEY}

        time:
          enabled: true

        weather:
          enabled: true
          api-key: ${WEATHER_API_KEY}

        baidu:
          map:
            apiKey: 8j3In53BNTJGesDAqRZvVlkDJ0VayzK7

    dashscope:
      api-key: sk-6b76c9f5936a4a5d8facb6daa5cd3b58
